kq1 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq1.place(x=400,y=130)
        kq2 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq2.place(x=720,y=130)
        kq3 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq3.place(x=1040,y=130)
        kq4 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq4.place(x=80,y=300)
        kq5 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq5.place(x=400,y=300)
        kq6 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq6.place(x=720,y=300)
        kq7 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq7.place(x=1040,y=300)
        kq8 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq8.place(x=80,y=470)
        kq9 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq9.place(x=400,y=470)
        kq10 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq10.place(x=720,y=470)
        kq11 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq11.place(x=1040,y=470)
        kq12 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq12.place(x=80,y=640)
        kq13 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq13.place(x=400,y=640)
        kq14 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq14.place(x=720,y=640)
        kq15 = Button(root, text="Submit", fg="Black",bg="green", font="arial 15 bold",width=20,height=5,command= taouser)
        kq15.place(x=1040,y=640)